//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSastiServices.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class STPService
    {
        public int ID { get; set; }
        public string ServiceName { get; set; }
        public string ServiceDescrption { get; set; }
        public int STPServiceTypeID { get; set; }
        public bool IsAvailible { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public int FuelTypeId { get; set; }
        public int UnitTypeId { get; set; }
        public decimal ServiceRate { get; set; }
    
        public virtual STPServicesFuelType STPServicesFuelType { get; set; }
        public virtual STPServicesUnitType STPServicesUnitType { get; set; }
        public virtual STPServiceType STPServiceType { get; set; }
    }
}
